name: Retrieve GitHub Secret via env

on:
  [push]

jobs:
  get-secret:
    runs-on: ubuntu-latest
    steps:
      - name: Assign secret to env variable and use it
        run: |
          echo "Secret value is: $MY_SECRET"
        env:
          MY_SECRET: ${{ secrets.GH_TOKEN }}
