name: Sync All Secrets to AWS Secrets Manager

on:
  push:
    branches:
      - kamal  # Trigger only on the 'kamal' branch

jobs:
  sync-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          ref: kamal  # Ensure the correct branch is checked out

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y jq python3-pip
          pip3 install boto3 requests

      - name: Verify AWS CLI Installation
        run: aws --version

      - name: Configure AWS CLI
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set region ${{ secrets.AWS_REGION }}

      - name: List and Copy GitHub Secrets to AWS
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # GitHub token with repo read access
          AWS_REGION: ${{ secrets.AWS_REGION }}
        run: python3 scripts/store_secret.py  # Running the updated script

